/**
 * Staging Runtime Foundation — Dev-only Secret Generator
 *
 * Emits a `.env.staging.local` template with cryptographically strong
 * random values for the four secret keys the staging gate requires
 * (ENCRYPTION_KEY, SECRETS_ENCRYPTION_KEY, COOKIE_SECRET, JWT_SECRET).
 *
 * **NOT for production.** The whole point of this script is to give a
 * developer running staging tests on their own machine a deterministic,
 * one-command path to a complete env file. Real staging hosts must
 * source these values from the secrets manager, not from this script.
 *
 * Usage:
 *   pnpm run staging:generate-secrets           # writes .env.staging.local
 *   pnpm run staging:generate-secrets --print   # prints to stdout, no write
 *   pnpm run staging:generate-secrets --force   # overwrite existing file
 *
 * The output file is gitignored (see .gitignore additions in this PR).
 */

import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const OUTPUT_FILE = ".env.staging.local";

const HEADER = `# ============================================================
# .env.staging.local — DEV-ONLY staging env, generated by
# scripts/staging-foundation/generate-dev-secrets.ts
#
# This file is gitignored. Do NOT commit. Do NOT use the values
# below for production — they are random per-developer and have
# no rotation discipline.
#
# Required by docs/deployment/staging-runtime-foundation.md and
# scripts/staging-foundation/preflight.ts.
# ============================================================
`;

interface RenderedEnv {
  body: string;
  generatedKeys: string[];
}

export function renderDevEnv(): RenderedEnv {
  const enc = (n: number): string => randomBytes(n).toString("hex");

  // Encryption keys: 32 bytes (AES-256) → 64 hex chars.
  // Cookie / JWT secrets: 32 bytes URL-safe → 43-char base64url.
  const generated = {
    ENCRYPTION_KEY: enc(32),
    SECRETS_ENCRYPTION_KEY: enc(32),
    COOKIE_SECRET: randomBytes(32).toString("base64url"),
    JWT_SECRET: randomBytes(32).toString("base64url"),
  };

  const body = `${HEADER}
# ─── Required by preflight ────────────────────────────────
# DATABASE_URL — point at a staging Postgres reachable from this host.
DATABASE_URL=postgres://localhost:5432/mynewap1claude

# OPA_URL — point at a real OPA instance. opa.example.com is rejected.
# Leave commented to keep preflight blocked until staging OPA is ready.
# OPA_URL=http://localhost:8181

# Random per-developer secrets (generated by generate-dev-secrets.ts):
ENCRYPTION_KEY=${generated.ENCRYPTION_KEY}
SECRETS_ENCRYPTION_KEY=${generated.SECRETS_ENCRYPTION_KEY}
COOKIE_SECRET=${generated.COOKIE_SECRET}
JWT_SECRET=${generated.JWT_SECRET}

# ─── Component-scoped (Phase 4 / Phase 5) — optional ──────
# GRAPHRAG_WORKER_URL=
# DATA_ACQUISITION_WORKER_URL=
# EXTERNAL_ORCHESTRATOR_URL=
# REDIS_URL=

# S3 connector
# S3_BUCKET=
# S3_REGION=
# S3_ACCESS_KEY_ID=
# S3_SECRET_ACCESS_KEY=

# GDrive connector
# GDRIVE_CLIENT_ID=
# GDRIVE_CLIENT_SECRET=

# GitHub connector
# GITHUB_APP_ID=
# GITHUB_PRIVATE_KEY=

# ─── Mode flag ────────────────────────────────────────────
TEST_MODE=staging-integration
`;

  return { body, generatedKeys: Object.keys(generated) };
}

function parseArgs(argv: string[]): { print: boolean; force: boolean } {
  return {
    print: argv.includes("--print"),
    force: argv.includes("--force"),
  };
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  const { body } = renderDevEnv();

  if (args.print) {
    process.stdout.write(body);
    process.exit(0);
  }

  const target = resolve(process.cwd(), OUTPUT_FILE);
  if (existsSync(target) && !args.force) {
    process.stderr.write(
      `[generate-dev-secrets] ${OUTPUT_FILE} already exists. Re-run with --force to overwrite, or remove the file first.\n`,
    );
    process.exit(1);
  }

  writeFileSync(target, body, { encoding: "utf8", mode: 0o600 });
  process.stdout.write(
    `[generate-dev-secrets] wrote ${OUTPUT_FILE} with random per-developer secrets (mode 0600).\n` +
      "[generate-dev-secrets] Source it before running staging integration tests:\n" +
      `[generate-dev-secrets]   set -a; source ${OUTPUT_FILE}; set +a\n` +
      "[generate-dev-secrets] Or use direnv / dotenv-cli.\n",
  );
  process.exit(0);
}

const isMain =
  typeof require !== "undefined" && require.main === module
    ? true
    : import.meta.url === `file://${process.argv[1]}`;

if (isMain) {
  main();
}
