/**
 * PROV Mapper
 *
 * Maps KGIA provenance data to PROV-O (Provenance Ontology) triples.
 * Supports: prov:Entity, prov:Activity, prov:Agent, prov:wasDerivedFrom,
 * prov:wasGeneratedBy, prov:wasAttributedTo, prov:used.
 */

import type { ProvenanceRef } from "../../../domain/types";

export interface ProvTriple {
  subject: string;
  predicate: string;
  object: string;
}

const PROV = "http://www.w3.org/ns/prov#";

/**
 * Convert KGIA provenance refs to PROV-O triples.
 */
export function mapToProvTriples(
  runId: number,
  refs: ProvenanceRef[]
): ProvTriple[] {
  const triples: ProvTriple[] = [];
  const answerUri = `kgia:answer/${runId}`;
  const activityUri = `kgia:run/${runId}`;

  // The answer is a prov:Entity
  triples.push({
    subject: answerUri,
    predicate: `${PROV}type`,
    object: `${PROV}Entity`,
  });

  // The run is a prov:Activity
  triples.push({
    subject: activityUri,
    predicate: `${PROV}type`,
    object: `${PROV}Activity`,
  });

  // Answer was generated by the run
  triples.push({
    subject: answerUri,
    predicate: `${PROV}wasGeneratedBy`,
    object: activityUri,
  });

  for (const ref of refs) {
    const sourceUri = `kgia:source/${ref.sourceType}/${encodeURIComponent(ref.sourceRef)}`;

    // Source is a prov:Entity
    triples.push({
      subject: sourceUri,
      predicate: `${PROV}type`,
      object: `${PROV}Entity`,
    });

    // Answer was derived from source
    triples.push({
      subject: answerUri,
      predicate: `${PROV}wasDerivedFrom`,
      object: sourceUri,
    });

    // Run used the source
    triples.push({
      subject: activityUri,
      predicate: `${PROV}used`,
      object: sourceUri,
    });
  }

  return triples;
}

/**
 * Serialize PROV triples to N-Triples format.
 */
export function serializeToNTriples(triples: ProvTriple[]): string {
  return triples
    .map((t) => {
      const s = t.subject.startsWith("http") ? `<${t.subject}>` : `<urn:${t.subject}>`;
      const p = `<${t.predicate}>`;
      const o = t.object.startsWith("http") ? `<${t.object}>` : `<urn:${t.object}>`;
      return `${s} ${p} ${o} .`;
    })
    .join("\n");
}
