DROP TABLE `agents`;--> statement-breakpoint
DROP TABLE `conversations`;--> statement-breakpoint
DROP TABLE `document_chunks`;--> statement-breakpoint
DROP TABLE `documents`;--> statement-breakpoint
DROP TABLE `download_analytics`;--> statement-breakpoint
DROP TABLE `hardware_profiles`;--> statement-breakpoint
DROP TABLE `knowledge_packs`;--> statement-breakpoint
DROP TABLE `messages`;--> statement-breakpoint
DROP TABLE `model_benchmarks`;--> statement-breakpoint
DROP TABLE `model_configs`;--> statement-breakpoint
DROP TABLE `model_conversions`;--> statement-breakpoint
DROP TABLE `model_downloads`;--> statement-breakpoint
DROP TABLE `model_share_references`;--> statement-breakpoint
DROP TABLE `model_shares`;--> statement-breakpoint
DROP TABLE `model_versions`;--> statement-breakpoint
DROP TABLE `models`;--> statement-breakpoint
DROP TABLE `plugins`;--> statement-breakpoint
DROP TABLE `provider_health_checks`;--> statement-breakpoint
DROP TABLE `provider_metrics`;--> statement-breakpoint
DROP TABLE `provider_usage`;--> statement-breakpoint
DROP TABLE `providers`;--> statement-breakpoint
DROP TABLE `system_settings`;--> statement-breakpoint
DROP TABLE `workflow_runs`;--> statement-breakpoint
DROP TABLE `workflows`;--> statement-breakpoint
DROP TABLE `workspace_members`;--> statement-breakpoint
DROP TABLE `workspace_providers`;--> statement-breakpoint
DROP TABLE `workspaces`;