/**
 * Graph Algorithm public-api barrel — Phase 26 §T-G.5.
 */

export {
  GRAPH_ALGORITHM_KINDS,
  GRAPH_ALGORITHM_BACKEND_SUPPORT,
  GRAPH_ALGORITHM_METADATA,
  GraphAlgorithmMaxNodesOutOfRangeError,
  GraphAlgorithmMaxIterationsOutOfRangeError,
  isGraphAlgorithmKind,
  normalizeAlgorithmMaxNodes,
  normalizeAlgorithmMaxIterations,
  preflightAlgorithmRequest,
  listAlgorithmsTriggeringAuraUpgrade,
  listAlgorithmsAvailableOnCe,
  summarizeGraphAlgorithmCoverage,
  GRAPH_ALGORITHM_BACKEND_SUPPORT_METADATA,
  getGraphAlgorithmBackendSupportMetadata,
  GRAPH_ALGORITHM_CATEGORIES,
  GRAPH_ALGORITHM_KIND_METADATA,
  getGraphAlgorithmKindMetadata,
  GRAPH_ALGORITHM_PREFLIGHT_DECISIONS,
  GRAPH_ALGORITHM_PREFLIGHT_DECISION_METADATA,
  getGraphAlgorithmPreflightDecisionMetadata,
  type GraphAlgorithmKind,
  type GraphAlgorithmBackendSupport,
  type GraphAlgorithmMetadata,
  type GraphAlgorithmRequest,
  type GraphAlgorithmResult,
  type GraphAlgorithmResultRow,
  type GraphAlgorithmPreflightDecision,
  type GraphAlgorithmPreflightOutcome,
  type GraphAlgorithmCoverageSummary,
  type GraphAlgorithmBackendSupportMetadata,
  type GraphAlgorithmCategory,
  type GraphAlgorithmKindMetadata,
  type GraphAlgorithmPreflightDecisionMetadata,
} from "./contracts.js";
