-- Create trigger_registry table
CREATE TABLE IF NOT EXISTS trigger_registry (
  id INT AUTO_INCREMENT PRIMARY KEY,
  typeId VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(50) NOT NULL,
  semanticVersion VARCHAR(20) NOT NULL,
  icon VARCHAR(50),
  classification ENUM('external', 'time-based', 'manual') NOT NULL,
  isDeterministic BOOLEAN NOT NULL,
  isIdempotent BOOLEAN NOT NULL,
  safeByDefault BOOLEAN NOT NULL DEFAULT TRUE,
  intentDoc TEXT NOT NULL,
  configSchema JSON NOT NULL,
  configSchemaVersion INT NOT NULL DEFAULT 1,
  defaultConfig JSON,
  uiRenderer TEXT,
  requiredFields JSON,
  unsafeOptions JSON,
  validationRules JSON,
  samplePayload JSON,
  inputContract JSON,
  outputContract JSON NOT NULL,
  outputTypes JSON,
  initialWorkflowSchema JSON,
  executionMode ENUM('sync', 'async') NOT NULL,
  blockingBehavior ENUM('blocking', 'non-blocking') NOT NULL,
  retryPolicy JSON,
  timeoutPolicy JSON,
  failureHandling JSON,
  stateTier ENUM('ephemeral', 'durable') NOT NULL,
  maxStateSize INT,
  concurrentIsolation TEXT,
  compensationStrategy TEXT,
  workflowFailureHandler JSON,
  idempotencyKeyField VARCHAR(100),
  requiredPermissions JSON,
  riskLevel ENUM('safe', 'restricted', 'privileged') NOT NULL,
  preExecutionPolicies JSON,
  secretFields JSON,
  tenantScoped BOOLEAN NOT NULL DEFAULT TRUE,
  tenantIsolation TEXT,
  metricsConfig JSON,
  logFields JSON,
  errorClassification JSON,
  performanceProfile ENUM('light', 'standard', 'heavy') NOT NULL,
  latencySLA JSON,
  throughputExpectation INT,
  degradationBehavior TEXT,
  rateLimits JSON,
  costQuotas JSON,
  backpressureStrategy TEXT,
  purposeDoc TEXT NOT NULL,
  useCases JSON,
  failureModes JSON,
  securityConsiderations TEXT,
  examples JSON,
  testCoverage JSON,
  dryRunSupported BOOLEAN NOT NULL DEFAULT FALSE,
  simulationConfig JSON,
  deprecationNotice TEXT,
  migrationPath TEXT,
  replacementTypeId VARCHAR(100),
  subWorkflowSupport BOOLEAN NOT NULL DEFAULT FALSE,
  maxNestingDepth INT DEFAULT 5,
  variableScopingRules TEXT,
  failureBubblingRules TEXT,
  handlerCode TEXT,
  handlerType ENUM('inline', 'external', 'webhook') NOT NULL,
  handlerEndpoint VARCHAR(500),
  requiresNetwork BOOLEAN NOT NULL DEFAULT FALSE,
  requiresSecrets BOOLEAN NOT NULL DEFAULT FALSE,
  hasSideEffects BOOLEAN NOT NULL DEFAULT FALSE,
  hasCost BOOLEAN NOT NULL DEFAULT FALSE,
  status ENUM('draft', 'pending_approval', 'approved', 'rejected', 'deprecated') NOT NULL DEFAULT 'draft',
  approvedBy INT,
  approvedAt TIMESTAMP,
  rejectionReason TEXT,
  criticalViolations INT NOT NULL DEFAULT 0,
  majorIssues INT NOT NULL DEFAULT 0,
  complianceScore INT,
  lastValidated TIMESTAMP,
  createdBy INT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create action_registry table
CREATE TABLE IF NOT EXISTS action_registry (
  id INT AUTO_INCREMENT PRIMARY KEY,
  typeId VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(50) NOT NULL,
  semanticVersion VARCHAR(20) NOT NULL,
  icon VARCHAR(50),
  classification ENUM('side-effecting', 'transformational', 'control-flow', 'ai-agent') NOT NULL,
  isDeterministic BOOLEAN NOT NULL,
  isIdempotent BOOLEAN NOT NULL,
  safeByDefault BOOLEAN NOT NULL DEFAULT TRUE,
  intentDoc TEXT NOT NULL,
  sideEffects JSON NOT NULL,
  configSchema JSON NOT NULL,
  configSchemaVersion INT NOT NULL DEFAULT 1,
  defaultConfig JSON,
  uiRenderer TEXT,
  requiredFields JSON,
  unsafeOptions JSON,
  validationRules JSON,
  retryBehaviorVisible BOOLEAN NOT NULL DEFAULT TRUE,
  timeoutBehaviorVisible BOOLEAN NOT NULL DEFAULT TRUE,
  failureBehaviorVisible BOOLEAN NOT NULL DEFAULT TRUE,
  inputContract JSON NOT NULL,
  outputContract JSON NOT NULL,
  outputTypes JSON,
  noGlobalMutation BOOLEAN NOT NULL DEFAULT TRUE,
  executionMode ENUM('sync', 'async') NOT NULL,
  blockingBehavior ENUM('blocking', 'non-blocking') NOT NULL,
  retryPolicy JSON,
  timeoutPolicy JSON,
  failureHandling JSON,
  stateTier ENUM('ephemeral', 'durable') NOT NULL,
  maxStateSize INT,
  concurrentIsolation TEXT,
  compensationStrategy TEXT NOT NULL,
  compensationAutomation JSON,
  workflowFailureHandler JSON,
  idempotencyKeyField VARCHAR(100),
  partialRollbackPaths JSON,
  requiredPermissions JSON,
  riskLevel ENUM('safe', 'restricted', 'privileged') NOT NULL,
  preExecutionPolicies JSON,
  secretFields JSON,
  promptVariableSanitization JSON,
  tokenCap INT,
  costCap INT,
  outputSchema JSON,
  confidenceScoreExposed BOOLEAN DEFAULT FALSE,
  highRiskDefinition JSON,
  humanInLoopRequired BOOLEAN DEFAULT FALSE,
  tenantScoped BOOLEAN NOT NULL DEFAULT TRUE,
  tenantIsolation TEXT,
  metricsConfig JSON,
  logFields JSON,
  errorClassification JSON,
  performanceProfile ENUM('light', 'standard', 'heavy') NOT NULL,
  latencySLA JSON,
  throughputExpectation INT,
  degradationBehavior TEXT,
  rateLimits JSON,
  costQuotas JSON,
  backpressureStrategy TEXT,
  purposeDoc TEXT NOT NULL,
  useCases JSON,
  failureModes JSON,
  securityConsiderations TEXT,
  examples JSON,
  testCoverage JSON,
  dryRunSupported BOOLEAN NOT NULL DEFAULT FALSE,
  simulationConfig JSON,
  deprecationNotice TEXT,
  migrationPath TEXT,
  replacementTypeId VARCHAR(100),
  subWorkflowSupport BOOLEAN NOT NULL DEFAULT FALSE,
  maxNestingDepth INT DEFAULT 5,
  variableScopingRules TEXT,
  failureBubblingRules TEXT,
  handlerCode TEXT,
  handlerType ENUM('inline', 'external', 'api') NOT NULL,
  handlerEndpoint VARCHAR(500),
  requiresNetwork BOOLEAN NOT NULL DEFAULT FALSE,
  requiresSecrets BOOLEAN NOT NULL DEFAULT FALSE,
  hasSideEffects BOOLEAN NOT NULL DEFAULT FALSE,
  hasCost BOOLEAN NOT NULL DEFAULT FALSE,
  status ENUM('draft', 'pending_approval', 'approved', 'rejected', 'deprecated') NOT NULL DEFAULT 'draft',
  approvedBy INT,
  approvedAt TIMESTAMP,
  rejectionReason TEXT,
  criticalViolations INT NOT NULL DEFAULT 0,
  majorIssues INT NOT NULL DEFAULT 0,
  complianceScore INT,
  lastValidated TIMESTAMP,
  createdBy INT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
