/**
 * PS — Canonical Navigation Configuration
 *
 * Follows the shared ModuleNavConfig contract pattern (same as PM Central).
 * PS Ideation is a sub-module of the Projects System.
 */

import type { ModuleNavConfig, ModuleNavItem } from "./moduleNavTypes";

export const PS_NAV_CONFIG: ModuleNavConfig = {
  id: "projects-system",
  label: "Projects System",
  baseRoute: "/ps",

  sections: [
    {
      id: "catalog",
      label: "Catalog",
      iconHint: "book-open",
      purpose: "Browse available project system types and templates.",
      href: "/ps/catalog",
      requiredAction: "ps.catalog.read",
      scopeType: "all",
      visibilityMode: "show",
      backedBy: "existing-page",
      backendDomain: "catalog",
      implementationStatus: "live",
      currentRoute: "/ps/catalog",
      currentComponent: "PSCatalogPage",
      items: [
        {
          id: "ps-catalog",
          label: "PS Catalog",
          href: "/ps/catalog",
          section: "catalog",
          iconHint: "book-open",
          purpose: "Browse project system types.",
          requiredAction: "ps.catalog.read",
          scopeType: "all",
          visibilityMode: "show",
          backedBy: "existing-page",
          backendDomain: "catalog",
          implementationStatus: "live",
          currentRoute: "/ps/catalog",
          currentComponent: "PSCatalogPage",
        },
      ],
    },
    {
      id: "ideation",
      label: "Ideation",
      iconHint: "lightbulb",
      purpose: "Pre-project intake, concept framing, and ideation workflow.",
      href: "/ps/ideation",
      requiredAction: "ps.ideation.read",
      scopeType: "all",
      visibilityMode: "show",
      backedBy: "new-page",
      backendDomain: "ideation",
      implementationStatus: "live",
      currentRoute: "/ps/ideation",
      currentComponent: "PSIdeationPage",
      items: [
        {
          id: "ps-ideation-list",
          label: "Ideation Records",
          href: "/ps/ideation",
          section: "ideation",
          iconHint: "lightbulb",
          purpose: "List and manage ideation records.",
          requiredAction: "ps.ideation.read",
          scopeType: "all",
          visibilityMode: "show",
          backedBy: "new-page",
          backendDomain: "ideation",
          implementationStatus: "live",
          currentRoute: "/ps/ideation",
          currentComponent: "PSIdeationPage",
        },
        {
          id: "ps-ideation-new",
          label: "New Ideation",
          href: "/ps/ideation/new",
          section: "ideation",
          iconHint: "plus",
          purpose: "Start a new ideation record.",
          requiredAction: "ps.ideation.write",
          scopeType: "all",
          visibilityMode: "show",
          backedBy: "new-page",
          backendDomain: "ideation",
          implementationStatus: "live",
          currentRoute: "/ps/ideation/new",
          currentComponent: "PSIdeationDetailPage",
        },
      ],
    },
    {
      id: "wizard",
      label: "Wizard",
      iconHint: "wand-2",
      purpose: "Classify and create project systems via the guided wizard.",
      href: "/ps/wizard",
      requiredAction: "ps.wizard.read",
      scopeType: "all",
      visibilityMode: "show",
      backedBy: "existing-page",
      backendDomain: "wizard",
      implementationStatus: "live",
      currentRoute: "/ps/wizard",
      currentComponent: "PSWizardPage",
      items: [
        {
          id: "ps-wizard",
          label: "PS Wizard",
          href: "/ps/wizard",
          section: "wizard",
          iconHint: "wand-2",
          purpose: "Run the PS classification wizard.",
          requiredAction: "ps.wizard.read",
          scopeType: "all",
          visibilityMode: "show",
          backedBy: "existing-page",
          backendDomain: "wizard",
          implementationStatus: "live",
          currentRoute: "/ps/wizard",
          currentComponent: "PSWizardPage",
        },
      ],
    },
    {
      id: "list",
      label: "Projects",
      iconHint: "list",
      purpose: "View all created PS projects.",
      href: "/ps/list",
      requiredAction: "ps.list.read",
      scopeType: "all",
      visibilityMode: "show",
      backedBy: "existing-page",
      backendDomain: "projects",
      implementationStatus: "live",
      currentRoute: "/ps/list",
      currentComponent: "PSListPage",
      items: [
        {
          id: "ps-list",
          label: "PS Projects",
          href: "/ps/list",
          section: "list",
          iconHint: "list",
          purpose: "Browse created PS projects.",
          requiredAction: "ps.list.read",
          scopeType: "all",
          visibilityMode: "show",
          backedBy: "existing-page",
          backendDomain: "projects",
          implementationStatus: "live",
          currentRoute: "/ps/list",
          currentComponent: "PSListPage",
        },
      ],
    },
    {
      id: "control-panel",
      label: "Control Panel",
      iconHint: "settings",
      purpose: "PS monitoring, KPIs, and administrative operations.",
      href: "/ps/control-panel",
      requiredAction: "ps.admin.read",
      scopeType: "all",
      visibilityMode: "show",
      backedBy: "existing-page",
      backendDomain: "monitoring",
      implementationStatus: "live",
      currentRoute: "/ps/control-panel",
      currentComponent: "PSControlPanelPage",
      items: [
        {
          id: "ps-control-panel",
          label: "Control Panel",
          href: "/ps/control-panel",
          section: "control-panel",
          iconHint: "settings",
          purpose: "Monitor PS system health and KPIs.",
          requiredAction: "ps.admin.read",
          scopeType: "all",
          visibilityMode: "show",
          backedBy: "existing-page",
          backendDomain: "monitoring",
          implementationStatus: "live",
          currentRoute: "/ps/control-panel",
          currentComponent: "PSControlPanelPage",
        },
      ],
    },
  ],
};

export function getAllPsNavItems(): ModuleNavItem[] {
  return PS_NAV_CONFIG.sections.flatMap((s) => s.items);
}
