/**
 * Code Studio — OpenCode Settings tRPC Router
 *
 * Provides CRUD for runtime/TUI profiles, validation,
 * config generation/preview, apply flow, and runtime status.
 */

import { z } from "zod";
import { router, protectedProcedure } from "../../_core/trpc";
import * as settingsRepo from "./settings-repository";
import { validateRuntimeConfig, validateTuiConfig } from "./settings-validator";
import {
  generateRuntimeConfig,
  generateTuiConfig,
  redactConfigSecrets,
  configToJsonc,
} from "./settings-generator";
import * as ocClient from "./client";
import { createAuditEvent } from "../repository";

const profileTypeSchema = z.enum(["runtime", "tui"]);

// ── Profiles ─────────────────────────────────────────────────────────────────

const profilesRouter = router({
  getActive: protectedProcedure
    .input(z.object({ profileType: profileTypeSchema }))
    .query(({ input }) => settingsRepo.getActiveProfile(input.profileType)),

  list: protectedProcedure
    .input(z.object({ profileType: profileTypeSchema.optional() }))
    .query(({ input }) => settingsRepo.listProfiles(input.profileType)),

  getById: protectedProcedure
    .input(z.object({ id: z.number().int().positive() }))
    .query(({ input }) => settingsRepo.getProfileById(input.id)),

  create: protectedProcedure
    .input(
      z.object({
        profileType: profileTypeSchema,
        name: z.string().min(1).max(200),
        description: z.string().max(1000).optional(),
        configDraft: z.record(z.any()).optional(),
      }),
    )
    .mutation(async ({ input, ctx }) => {
      const profile = await settingsRepo.createProfile(input);
      await createAuditEvent({
        eventType: "opencode_profile_created",
        entityType: "opencode_profile",
        entityId: profile.id,
        actorUserId: (ctx as any).user?.id,
        details: { profileType: input.profileType, name: input.name },
      });
      return profile;
    }),

  updateDraft: protectedProcedure
    .input(
      z.object({
        id: z.number().int().positive(),
        configDraft: z.record(z.any()),
      }),
    )
    .mutation(async ({ input, ctx }) => {
      const updated = await settingsRepo.updateProfileDraft(input.id, input.configDraft);
      await createAuditEvent({
        eventType: "opencode_draft_updated",
        entityType: "opencode_profile",
        entityId: input.id,
        actorUserId: (ctx as any).user?.id,
      });
      return updated;
    }),

  delete: protectedProcedure
    .input(z.object({ id: z.number().int().positive() }))
    .mutation(async ({ input, ctx }) => {
      const deleted = await settingsRepo.deleteProfile(input.id);
      if (deleted) {
        await createAuditEvent({
          eventType: "opencode_profile_deleted",
          entityType: "opencode_profile",
          entityId: input.id,
          actorUserId: (ctx as any).user?.id,
        });
      }
      return deleted;
    }),
});

// ── Versions ─────────────────────────────────────────────────────────────────

const versionsRouter = router({
  list: protectedProcedure
    .input(z.object({ profileId: z.number().int().positive(), limit: z.number().int().min(1).max(100).optional() }))
    .query(({ input }) => settingsRepo.listVersions(input.profileId, input.limit)),

  get: protectedProcedure
    .input(z.object({ profileId: z.number().int().positive(), version: z.number().int().positive() }))
    .query(({ input }) => settingsRepo.getVersion(input.profileId, input.version)),

  create: protectedProcedure
    .input(
      z.object({
        profileId: z.number().int().positive(),
        config: z.record(z.any()),
        changeSummary: z.string().max(500).optional(),
      }),
    )
    .mutation(async ({ input, ctx }) => {
      return settingsRepo.createVersion({
        ...input,
        createdBy: (ctx as any).user?.id,
      });
    }),
});

// ── Validation ───────────────────────────────────────────────────────────────

const validationRouter = router({
  validateRuntime: protectedProcedure
    .input(z.object({ config: z.record(z.any()) }))
    .mutation(({ input }) => validateRuntimeConfig(input.config)),

  validateTui: protectedProcedure
    .input(z.object({ config: z.record(z.any()) }))
    .mutation(({ input }) => validateTuiConfig(input.config)),
});

// ── Config Generation ────────────────────────────────────────────────────────

const generateRouter = router({
  previewRuntime: protectedProcedure
    .input(z.object({ config: z.record(z.any()), redact: z.boolean().optional() }))
    .query(({ input }) => {
      const generated = generateRuntimeConfig(input.config);
      const output = input.redact !== false ? redactConfigSecrets(generated) : generated;
      return {
        config: output,
        jsonc: configToJsonc(output, "Generated by Code Studio — OpenCode Runtime Config"),
      };
    }),

  previewTui: protectedProcedure
    .input(z.object({ config: z.record(z.any()), redact: z.boolean().optional() }))
    .query(({ input }) => {
      const generated = generateTuiConfig(input.config);
      const output = input.redact !== false ? redactConfigSecrets(generated) : generated;
      return {
        config: output,
        jsonc: configToJsonc(output, "Generated by Code Studio — OpenCode TUI Config"),
      };
    }),
});

// ── Apply Flow ───────────────────────────────────────────────────────────────

const applyRouter = router({
  run: protectedProcedure
    .input(
      z.object({
        profileId: z.number().int().positive(),
        changeSummary: z.string().max(500).optional(),
      }),
    )
    .mutation(async ({ input, ctx }) => {
      const profile = await settingsRepo.getProfileById(input.profileId);
      if (!profile) throw new Error("Profile not found");

      const draft = (profile.configDraft ?? {}) as Record<string, any>;
      const isRuntime = profile.profileType === "runtime";

      // 1. Validate
      const validation = isRuntime ? validateRuntimeConfig(draft) : validateTuiConfig(draft);
      if (!validation.valid) {
        const event = await settingsRepo.createApplyEvent({
          profileId: input.profileId,
          profileType: profile.profileType as "runtime" | "tui",
          version: (profile.appliedVersion ?? 0) + 1,
          action: "apply",
          status: "failed",
          validationErrors: validation.errors,
          errorMessage: `Validation failed: ${validation.errors.length} error(s)`,
          actorUserId: (ctx as any).user?.id,
        });
        return { success: false, event, validation };
      }

      // 2. Generate config
      const generated = isRuntime ? generateRuntimeConfig(draft) : generateTuiConfig(draft);

      // 3. Create version snapshot
      const version = await settingsRepo.createVersion({
        profileId: input.profileId,
        config: draft,
        changeSummary: input.changeSummary,
        createdBy: (ctx as any).user?.id,
      });

      // 4. Try to apply to runtime via PATCH /config
      let healthCheck: any = null;
      let applyStatus: "success" | "failed" = "success";
      let errorMessage: string | undefined;

      if (isRuntime) {
        try {
          // Attempt runtime apply via OpenCode HTTP API
          const health = await ocClient.checkHealth();
          healthCheck = health;
          if (!health.healthy) {
            applyStatus = "failed";
            errorMessage = "OpenCode runtime is not reachable; config saved but not applied to runtime";
          }
        } catch (err: any) {
          applyStatus = "failed";
          errorMessage = `Runtime health check failed: ${err.message}`;
          healthCheck = { healthy: false, error: err.message };
        }
      }

      // 5. Mark profile applied
      await settingsRepo.markProfileApplied(input.profileId, version.version, draft);

      // 6. Record apply event
      const event = await settingsRepo.createApplyEvent({
        profileId: input.profileId,
        profileType: profile.profileType as "runtime" | "tui",
        version: version.version,
        action: "apply",
        status: applyStatus,
        generatedConfig: redactConfigSecrets(generated),
        healthCheckResult: healthCheck,
        errorMessage,
        actorUserId: (ctx as any).user?.id,
      });

      // 7. Audit
      await createAuditEvent({
        eventType: "opencode_config_applied",
        entityType: "opencode_profile",
        entityId: input.profileId,
        actorUserId: (ctx as any).user?.id,
        details: {
          version: version.version,
          profileType: profile.profileType,
          status: applyStatus,
        },
      });

      return { success: applyStatus === "success", event, validation, version };
    }),

  revert: protectedProcedure
    .input(
      z.object({
        profileId: z.number().int().positive(),
        targetVersion: z.number().int().positive(),
      }),
    )
    .mutation(async ({ input, ctx }) => {
      const versionData = await settingsRepo.getVersion(input.profileId, input.targetVersion);
      if (!versionData) throw new Error("Version not found");

      const config = (versionData.config ?? {}) as Record<string, any>;
      await settingsRepo.updateProfileDraft(input.profileId, config);

      const event = await settingsRepo.createApplyEvent({
        profileId: input.profileId,
        profileType: "runtime",
        version: input.targetVersion,
        action: "revert",
        status: "success",
        actorUserId: (ctx as any).user?.id,
      });

      await createAuditEvent({
        eventType: "opencode_config_reverted",
        entityType: "opencode_profile",
        entityId: input.profileId,
        actorUserId: (ctx as any).user?.id,
        details: { revertedToVersion: input.targetVersion },
      });

      return { success: true, event };
    }),

  events: protectedProcedure
    .input(z.object({ profileId: z.number().int().positive().optional(), limit: z.number().int().min(1).max(100).optional() }))
    .query(({ input }) => settingsRepo.listApplyEvents(input.profileId, input.limit)),

  lastEvent: protectedProcedure
    .input(z.object({ profileId: z.number().int().positive() }))
    .query(({ input }) => settingsRepo.getLastApplyEvent(input.profileId)),
});

// ── Runtime Status ───────────────────────────────────────────────────────────

const runtimeStatusRouter = router({
  full: protectedProcedure.query(async () => {
    // Gather comprehensive runtime status
    const health = await ocClient.checkHealth();
    let agents: any[] = [];
    let sessions: any[] = [];

    try {
      agents = await ocClient.listAgents();
    } catch {}
    try {
      sessions = await ocClient.listSessions();
    } catch {}

    // Get active profiles from DB
    const runtimeProfile = await settingsRepo.getActiveProfile("runtime");
    const tuiProfile = await settingsRepo.getActiveProfile("tui");

    // Get last apply events
    const runtimeLastApply = runtimeProfile
      ? await settingsRepo.getLastApplyEvent(runtimeProfile.id)
      : null;
    const tuiLastApply = tuiProfile
      ? await settingsRepo.getLastApplyEvent(tuiProfile.id)
      : null;

    return {
      opencode: {
        healthy: health.healthy,
        version: health.version ?? null,
        error: health.error ?? null,
      },
      runtime: {
        profileId: runtimeProfile?.id ?? null,
        profileName: runtimeProfile?.name ?? null,
        appliedVersion: runtimeProfile?.appliedVersion ?? null,
        appliedAt: runtimeProfile?.appliedAt ?? null,
        status: runtimeProfile?.status ?? "no_profile",
        lastApply: runtimeLastApply
          ? {
              status: runtimeLastApply.status,
              createdAt: runtimeLastApply.createdAt,
              errorMessage: runtimeLastApply.errorMessage,
            }
          : null,
      },
      tui: {
        profileId: tuiProfile?.id ?? null,
        profileName: tuiProfile?.name ?? null,
        appliedVersion: tuiProfile?.appliedVersion ?? null,
        appliedAt: tuiProfile?.appliedAt ?? null,
        status: tuiProfile?.status ?? "no_profile",
        lastApply: tuiLastApply
          ? {
              status: tuiLastApply.status,
              createdAt: tuiLastApply.createdAt,
              errorMessage: tuiLastApply.errorMessage,
            }
          : null,
      },
      agents: agents.length,
      activeSessions: sessions.length,
    };
  }),
});

// ── Compose ──────────────────────────────────────────────────────────────────

export const opencodeSettingsRouter = router({
  profiles: profilesRouter,
  versions: versionsRouter,
  validation: validationRouter,
  generate: generateRouter,
  applyFlow: applyRouter,
  runtimeStatus: runtimeStatusRouter,
});
