/**
 * Markdown Reporter — outputs validation report as readable markdown
 */

import type { ValidationReport } from "../index";

export function mdReporter(report: ValidationReport): string {
  const lines: string[] = [];

  lines.push("# Governance Enforcement Validation Report");
  lines.push("");
  lines.push(`**Timestamp:** ${report.timestamp}`);
  lines.push(`**Verdict:** ${report.verdict === "PASS" ? "PASS" : "**FAIL**"}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Probes | ${report.summary.total} |`);
  lines.push(`| Passed | ${report.summary.passed} |`);
  lines.push(`| Failed | ${report.summary.failed} |`);
  lines.push(`| Warned | ${report.summary.warned} |`);
  lines.push(`| Critical Findings | ${report.summary.criticalFindings} |`);
  lines.push(`| High Findings | ${report.summary.highFindings} |`);
  lines.push("");

  lines.push("## Probe Results");
  lines.push("");

  for (const probe of report.probes) {
    const icon = probe.status === "PASS" ? "+" : probe.status === "FAIL" ? "x" : "!";
    lines.push(`### [${icon}] ${probe.probeId}: ${probe.probeName} — ${probe.status}`);
    lines.push("");
    lines.push(`> ${probe.summary}`);
    lines.push("");

    if (probe.findings.length > 0) {
      lines.push("| Severity | Title | File | Line |");
      lines.push("|----------|-------|------|------|");
      for (const f of probe.findings) {
        lines.push(`| ${f.severity.toUpperCase()} | ${f.title} | \`${f.file}\` | ${f.line} |`);
      }
      lines.push("");

      // Detail for critical/high findings
      const important = probe.findings.filter((f) => f.severity === "critical" || f.severity === "high");
      if (important.length > 0) {
        lines.push("**Details:**");
        lines.push("");
        for (const f of important) {
          lines.push(`- **${f.title}** (\`${f.file}:${f.line}\`)`);
          lines.push(`  - ${f.detail}`);
          if (f.attack) lines.push(`  - Attack: ${f.attack}`);
          if (f.expected) lines.push(`  - Expected: ${f.expected}`);
          if (f.actual) lines.push(`  - Actual: ${f.actual}`);
        }
        lines.push("");
      }
    }
  }

  lines.push("---");
  lines.push(`*Generated by Governance Enforcement Validation Harness v${report.version}*`);

  return lines.join("\n");
}
