/**
 * Module Nav Scaffolding Utility — Phase 14
 *
 * Generates starter files for a new module adopting the Carbon SideNav standard.
 *
 * Usage:
 *   npx tsx scripts/scaffold-module-nav.ts <module-id> "<Module Label>" /<base-route>
 *
 * Example:
 *   npx tsx scripts/scaffold-module-nav.ts finance "Finance" /finance
 *
 * Generated files:
 *   - client/src/config/<moduleId>NavConfig.ts    (nav config skeleton)
 *   - Governance-Centrale/modules/<moduleId>/README.md (governance pack index)
 *   - Governance-Centrale/modules/<moduleId>/MODULE_GOVERNANCE_PROFILE.md (profile)
 *
 * Also prints a registry entry to paste into moduleNavRegistry.ts.
 *
 * This script does NOT:
 *   - Modify App.tsx (routes must be added manually)
 *   - Modify moduleNavRegistry.ts (entry must be pasted manually)
 *   - Create validators or test files (add these as needed)
 *   - Overwrite existing files (exits with error if files exist)
 */

import * as fs from "fs";
import * as path from "path";

// ---------------------------------------------------------------------------
// Parse arguments
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);

if (args.length < 3) {
  console.error("Usage: npx tsx scripts/scaffold-module-nav.ts <module-id> \"<Module Label>\" /<base-route>");
  console.error("Example: npx tsx scripts/scaffold-module-nav.ts finance \"Finance\" /finance");
  process.exit(1);
}

const [moduleId, moduleLabel, baseRoute] = args;

if (!moduleId.match(/^[a-z][a-z0-9-]*$/)) {
  console.error(`Error: module-id must be lowercase alphanumeric with dashes (got: ${moduleId})`);
  process.exit(1);
}

if (!baseRoute.startsWith("/")) {
  console.error(`Error: base-route must start with / (got: ${baseRoute})`);
  process.exit(1);
}

// Derive camelCase config name from module-id (e.g., "finance" -> "FINANCE", "digital-hq" -> "DIGITAL_HQ")
const constPrefix = moduleId.toUpperCase().replace(/-/g, "_");
const camelId = moduleId.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

const repoRoot = path.resolve(__dirname, "..");
const configDir = path.join(repoRoot, "client/src/config");
const govDir = path.join(repoRoot, "Governance-Centrale/modules", moduleId);

// ---------------------------------------------------------------------------
// Safety: don't overwrite existing files
// ---------------------------------------------------------------------------

const navConfigPath = path.join(configDir, `${camelId}NavConfig.ts`);
const govReadmePath = path.join(govDir, "README.md");
const govProfilePath = path.join(govDir, "MODULE_GOVERNANCE_PROFILE.md");

const existing = [navConfigPath, govReadmePath, govProfilePath].filter(fs.existsSync);
if (existing.length > 0) {
  console.error("Error: The following files already exist (will not overwrite):");
  existing.forEach((f) => console.error(`  ${path.relative(repoRoot, f)}`));
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Generate nav config
// ---------------------------------------------------------------------------

const navConfigContent = `/**
 * ${moduleLabel} Carbon SideNav — Canonical Navigation Configuration
 *
 * This file is the SINGLE SOURCE OF TRUTH for the ${moduleLabel} module
 * navigation model. All sidebar rendering, route resolution, permission
 * gating, and governance documentation should derive from this configuration.
 *
 * Generated by: scripts/scaffold-module-nav.ts
 * Date: ${new Date().toISOString().split("T")[0]}
 * Reference: HR implementation at client/src/config/hrNavConfig.ts
 * Standard: Governance-Centrale/global/MODULE_NAV_STANDARD.md
 */

import type {
  ScopeType,
  VisibilityMode,
  BackedBy,
  ImplementationStatus,
  ModuleNavItem,
  ModuleNavSection,
  ModuleNavConfig,
} from "../navigation/moduleNavTypes";

// ---------------------------------------------------------------------------
// Canonical Navigation Model
// ---------------------------------------------------------------------------

export const ${constPrefix}_NAV_CONFIG: ModuleNavConfig = {
  id: "${moduleId}",
  label: "${moduleLabel}",
  baseRoute: "${baseRoute}",

  sections: [
    // Add sections here. Example:
    // {
    //   id: "overview",
    //   label: "Overview",
    //   iconHint: "dashboard",
    //   purpose: "Module overview and quick actions.",
    //   href: "${baseRoute}/overview",
    //   requiredAction: "${moduleId}.overview.read",
    //   scopeType: "all",
    //   visibilityMode: "show",
    //   backedBy: "existing-page",
    //   backendDomain: "overview",
    //   implementationStatus: "live",
    //   items: [
    //     {
    //       id: "dashboard",
    //       label: "Dashboard",
    //       href: "${baseRoute}/overview/dashboard",
    //       section: "overview",
    //       purpose: "Module dashboard with key metrics.",
    //       requiredAction: "${moduleId}.overview.read",
    //       scopeType: "all",
    //       visibilityMode: "show",
    //       backedBy: "existing-page",
    //       backendDomain: "overview",
    //       implementationStatus: "live",
    //       currentRoute: "${baseRoute}",
    //       currentComponent: "${moduleLabel}DashboardPage",
    //     },
    //   ],
    // },
  ],
};

// ---------------------------------------------------------------------------
// Derived Helpers
// ---------------------------------------------------------------------------

/** Get all leaf items across all sections */
export function getAll${moduleLabel.replace(/\s+/g, "")}NavItems(): ModuleNavItem[] {
  return ${constPrefix}_NAV_CONFIG.sections.flatMap((s) => s.items);
}

/** Find a section by ID */
export function find${moduleLabel.replace(/\s+/g, "")}SectionById(id: string): ModuleNavSection | undefined {
  return ${constPrefix}_NAV_CONFIG.sections.find((s) => s.id === id);
}
`;

// ---------------------------------------------------------------------------
// Generate governance pack README
// ---------------------------------------------------------------------------

const govReadmeContent = `# ${moduleLabel} Module — Governance Pack

## Overview

This directory contains the governance documentation for the **${moduleLabel}** module.

## Module Identity

| Field | Value |
|---|---|
| Module key | \`${moduleId}\` |
| Base route | \`${baseRoute}\` |
| Nav config | \`client/src/config/${camelId}NavConfig.ts\` |
| Governance model | AGENTS.md 5-agent orchestration |

## Governance Pack Contents

| File | Purpose |
|---|---|
| [README.md](README.md) | This file — module overview and index |
| [MODULE_GOVERNANCE_PROFILE.md](MODULE_GOVERNANCE_PROFILE.md) | Governance identity card |

## TODO

- [ ] Add MODULE_CONTROL_SURFACE.md
- [ ] Add MODULE_RISKS.md
- [ ] Add MODULE_OPEN_GAPS.md
- [ ] Add MODULE_RUNTIME_REFERENCES.md
- [ ] Complete the governance profile
`;

// ---------------------------------------------------------------------------
// Generate governance profile
// ---------------------------------------------------------------------------

const govProfileContent = `# ${moduleLabel} Module — Governance Profile

## Document Status

- **Type:** Module governance identity card
- **Module:** ${moduleLabel}
- **Module ID:** ${moduleId}
- **Created:** ${new Date().toISOString().split("T")[0]}
- **Nav standard version:** 1.1.0

---

## 1. Module Classification

| Property | Value |
|---|---|
| Module key | \`${moduleId}\` |
| tRPC namespace | \`${moduleId}.*\` |
| Frontend route prefix | \`${baseRoute}/*\` |
| Backend domain path | \`server/${moduleId}/\` |
| Database prefix | \`${moduleId.replace(/-/g, "_")}_*\` tables |
| Current version | 1.0.0 |
| Adoption status | [pending / pilot / wave-N] |
| Compliance status | [pending / compliant / partially-compliant] |

---

## 2. Navigation Surface

| Metric | Value |
|---|---|
| Sections | [N] |
| Total items | [N] |
| Live items | [N] |
| Deferred items | [N] |
| Completion % | [N%] |

---

## 3. Permission Model

| Role | Actions | Notes |
|---|---|---|
| [role-name] | [list of actions] | [notes] |

---

## 4. Open Gaps

| Gap | Severity | Detail |
|---|---|---|
| [Description] | [H/M/L] | [Detail] |

---

## 5. Risks

| Risk | Severity | Mitigation |
|---|---|---|
| [Description] | [H/M/L] | [Strategy] |
`;

// ---------------------------------------------------------------------------
// Write files
// ---------------------------------------------------------------------------

fs.mkdirSync(path.dirname(navConfigPath), { recursive: true });
fs.mkdirSync(govDir, { recursive: true });

fs.writeFileSync(navConfigPath, navConfigContent, "utf-8");
fs.writeFileSync(govReadmePath, govReadmeContent, "utf-8");
fs.writeFileSync(govProfilePath, govProfileContent, "utf-8");

console.log("\\n✅ Module nav scaffolding generated successfully!\\n");
console.log("Files created:");
console.log(\`  client/src/config/\${camelId}NavConfig.ts\`);
console.log(\`  Governance-Centrale/modules/\${moduleId}/README.md\`);
console.log(\`  Governance-Centrale/modules/\${moduleId}/MODULE_GOVERNANCE_PROFILE.md\`);

console.log("\\n📋 Paste this entry into client/src/navigation/moduleNavRegistry.ts:\\n");
console.log(\`  {
    moduleId: "\${moduleId}",
    label: "\${moduleLabel}",
    baseRoute: "\${baseRoute}",
    adoptionStatus: "pilot",
    navConfigPath: "client/src/config/\${camelId}NavConfig.ts",
    navConfigExists: true,
    governancePackPath: "Governance-Centrale/modules/\${moduleId}/",
    governancePackExists: true,
    sectionCount: 0,   // Update after adding sections
    itemCount: 0,       // Update after adding items
    complianceStatus: "partially-compliant",
    exceptionStatus: "active",
    exceptionIds: [],   // Add exception IDs if needed
    validationPasses: null,
  },\`);

console.log("\\n📝 Next steps:");
console.log("  1. Add sections and items to the nav config");
console.log("  2. Paste the registry entry into moduleNavRegistry.ts");
console.log("  3. Add routes to App.tsx");
console.log("  4. Run: npx vitest run server/__tests__/module-nav-compliance.test.ts");
console.log("  5. Complete the governance pack docs");
console.log("  6. Update Governance-Centrale indexes");
console.log(\`  7. See: Governance-Centrale/global/MODULE_NAV_WORKFLOW.md\\n\`);
`;
